swagger: "2.0"
info:
  title: Medical Pricing Bot API
  description: API to make chat conversations with CHIA for Med Pricing. 
  version: "0.0.1"
  contact: 
    email: arunanand.karunakaran@cardinalhealth.com 
host: chia-med-pricing.apps.cf.np.cahcloud.com
basePath: /api/message
schemes:
  - https
consumes:
 - application/json
produces:
  - application/json
paths:
  '/api/medpricing':
    post:
      summary: 
      description: CHIA PCF endpoint for Medical Pricing
      operationId: hello
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
      age:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string